#!/bin/sh -e
#
# ser vars
PHP_VERSION=82

# Replace ENV vars in configuration files
tmpfile=$(mktemp)
cat /etc/php${PHP_VERSION}/conf.d/custom.ini | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpfile" > /dev/null
mv "$tmpfile" /etc/php${PHP_VERSION}/conf.d/custom.ini

tmpfile=$(mktemp)
cat /etc/php${PHP_VERSION}/php-fpm.d/www.conf | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpfile" > /dev/null
mv "$tmpfile" /etc/php${PHP_VERSION}/php-fpm.d/www.conf

# pipe stderr to stdout and run php-fpm
exec 2>&1
exec php-fpm${PHP_VERSION} -F
